version: '3.5'

services:
  db1_5_6_7:
    image: knoxmic/elasticsearch:5.6.7
    environment:
      - "cluster.name=dev_5_6_7_elasticsearch_cluster"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 7200:9200
      - 7300:9300
    volumes:
      - esdata1_5_6_7:/usr/share/elasticsearch/data
    restart: always

volumes:
  esdata1_5_6_7:
    driver: local
